name: Build & Push to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*" # Match all tags

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Extract metadata for Docker
      id: meta
      run: |
        # Always set these tags
        TAGS="${{ secrets.DOCKERHUB_USERNAME }}/laravel-octane-stack:latest,${{ secrets.DOCKERHUB_USERNAME }}/laravel-octane-stack:${{ github.sha }}"
        
        # Add tag if the event is a tag push
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
          TAGS="$TAGS,${{ secrets.DOCKERHUB_USERNAME }}/laravel-octane-stack:$VERSION"
        fi
        
        echo "tags=${TAGS}" >> $GITHUB_OUTPUT

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: |
          type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/laravel-octane-stack:latest
        cache-to: type=inline